### ISSUE TITLE
Implement Hybrid API's In basic Form

### ISSUE THREAD

**Issue by wolflord212312** [p0t4t0sandwich/TaterLib#7]
Ketting,magma,mohist,Arc

Atleast so we can get mods version of hybrid so on

**Comment by p0t4t0sandwich** [comment]
Redid the API setup to allow for registering API hooks, just need to implement them now.
And restructured things so that TaterLib only has to be on once side when there's a shared mod/plugin classpath, ie Arclight

**Comment by p0t4t0sandwich** [comment]
Arclight's had some interesting stuff for registering Forge events from plugins, but I skipped that bit for now since TaterLib effectively does the same
