### ISSUE TITLE
Issue Loading on GoldenForge due to paper Patches 

### ISSUE THREAD

**Issue by wolflord212312** [p0t4t0sandwich/TaterLib#71]
### Debug Information

https://mclo.gs/vR47aIf

### Description of behavior

Detects paper patches on load and try to load bukkit side instead of forge.

### Reproduction Steps

```markdown
Run on golden forge
Get error
```

### TaterLib Configuration

DOES NOT MATTER

### Additional context

To fix this we just need to get the [server branding](https://github.com/GoldenForge/GoldenForge/blob/611cf470e8b932872c97af64ccba2c759619c79a/src/main/java/net/minecraftforge/internal/BrandingControl.java#L77C1-L79C6)

as goldenforge does customize that.

**Comment by p0t4t0sandwich** [comment]
Probably will just do a basic reflect-check to grab `GoldenForgeEntryPoint`
Though the updated branding should show in the `Server#brand()` method in TaterLib itself.
